export const ADD_COMMENT = 'ADD_COMMENT'
export const LOAD_COMMENT = 'LOAD_COMMENTS'
export const COMMENT_LOADING = 'COMMENT_LOADING'
export const LOAD_DISEHS = 'LOAD_DISHES'
export const DISHES_LOADING = "DISHES-LOADING"
export const DISHES_FAILED = "DISHES_FAILED"